//22/08/2014
package com.ghtopo.javaghtopo;

import static GHTopoOperationnel.GeneralFunctions.sprintf;
import GHTopoOperationnel.TConvertisseurCoordonnees;
import GHTopoOperationnel.TToporobotStructure;
import static UtilsComposants.TOperationsSurComposants.remplirCombosListesSystem;

/**
 *
 * @author jean-pierre.cassou
 */
public class TCadreGeneral extends javax.swing.JPanel {
    private TToporobotStructure fDocTopo;
    private TConvertisseurCoordonnees myConvertisseur;
    public void initialiseCadreGeneral(TToporobotStructure t)
    {
        fDocTopo = t;
        editNomEtude.setText(fDocTopo.getNomEtude());
        editXPtRef.setText(sprintf("%.2f", fDocTopo.getPoint0X()));
        editYPtRef.setText(sprintf("%.2f", fDocTopo.getPoint0Y()));
        editZPtRef.setText(sprintf("%.2f", fDocTopo.getPoint0Z()));
        editCommentairesEtude.setText(fDocTopo.getCommentairesEtude());
        
        
        int WU = myConvertisseur.getIndexOfEPSG(fDocTopo.getCoordSystCodeEPSG());
        
        lbDescSystCoords.setText(fDocTopo.getCoordSystCodeGHTopo() + " - " +
                                 fDocTopo.getCoordSystCommentaire());
        
        cmbSystemesCoordonnees.setSelectedIndex(WU);
    }        
    /**
     * Creates new form TCadreGeneral
     */
    public TCadreGeneral() 
    {
        initComponents();
        myConvertisseur = new TConvertisseurCoordonnees();
        myConvertisseur.initialiser();    
        remplirCombosListesSystem(cmbSystemesCoordonnees, myConvertisseur);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editNomEtude = new javax.swing.JTextField();
        editXPtRef = new javax.swing.JTextField();
        editYPtRef = new javax.swing.JTextField();
        editZPtRef = new javax.swing.JTextField();
        cmbSystemesCoordonnees = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        editCommentairesEtude = new javax.swing.JTextField();
        lbDescSystCoords = new javax.swing.JLabel();

        editXPtRef.setText("0");

        editYPtRef.setText("0");
        editYPtRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editYPtRefActionPerformed(evt);
            }
        });

        editZPtRef.setText("0");

        cmbSystemesCoordonnees.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Nom étude");

        jLabel2.setText("X de référence");

        jLabel3.setText("Y de référence");

        jLabel4.setText("Z de référence");

        jLabel5.setText("Système de coordonnées");

        jLabel6.setText("Commentaires");

        editCommentairesEtude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCommentairesEtudeActionPerformed(evt);
            }
        });

        lbDescSystCoords.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(0, 48, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(editZPtRef, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(editYPtRef, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editXPtRef, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbSystemesCoordonnees, javax.swing.GroupLayout.Alignment.TRAILING, 0, 325, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 204, Short.MAX_VALUE))
                            .addComponent(lbDescSystCoords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(editCommentairesEtude)
                    .addComponent(editNomEtude))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editNomEtude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(editXPtRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editYPtRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cmbSystemesCoordonnees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editZPtRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(lbDescSystCoords))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(editCommentairesEtude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(149, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editYPtRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editYPtRefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editYPtRefActionPerformed

    private void editCommentairesEtudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCommentairesEtudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editCommentairesEtudeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbSystemesCoordonnees;
    private javax.swing.JTextField editCommentairesEtude;
    private javax.swing.JTextField editNomEtude;
    private javax.swing.JTextField editXPtRef;
    private javax.swing.JTextField editYPtRef;
    private javax.swing.JTextField editZPtRef;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbDescSystCoords;
    // End of variables declaration//GEN-END:variables
}
