/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.ghtopo.javaghtopo;

import static GHTopoOperationnel.GeneralFunctions.*;
import GHTopoOperationnel.TPalette256;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Paint;
import java.awt.Point;
import javax.swing.JComponent;
import org.jdom2.filter.Filters;

/**
 *
 * @author jean-pierre.cassou
 */
public class TCadrePalette256 extends javax.swing.JPanel 
{
    private int fCurrentIdxCouleur = 0;
    private int fcx = 0;
    private int fcy = 0;
    TPalette256 myPalette256;
    public int getIdxCouleur()
    {
        return fCurrentIdxCouleur;
    }       
    public void initialiser(TPalette256 P, int Idx)
    {
        myPalette256 = P;
        myPalette256.generateTOPOROBOTPalette();
        
        fCurrentIdxCouleur = Idx;
        this.repaint();
    }        
    public TCadrePalette256() {
        initComponents();      
         // redessin
        
    }
    private int getIdxPaletteByXY(int x, int y)
    {
       int Result = -1;
       int CCX    = trunc(this.getWidth() / 16);
       int CCY    = trunc(this.getHeight() / 16);
       int L      = trunc(y / CCY);
       int C      = trunc(x / CCX);
       //Label4.Caption:=Format('L%d C%d',[L,C]);
       Result = C * 16 + L;
       if (Result > 255) Result = -1;
       return Result;
    }        
    
    public void paint(Graphics g)        
    {
        try
        {    
            afficherMessage("paintComponent");
            // Appel de la méthode paintComponent de la classe mère
            //super.paintComponent(g);
            // Conversion en un contexte 2D
            Graphics2D g2 = (Graphics2D) g;
            //Graphics2D g2 = (Graphics2D) g; 
            int h = this.getHeight();
            int w = this.getWidth();
            g2.setColor(Color.GRAY);
            g2.fillRect(0, 0, w, h);
            fcx = trunc(w / 16);
            fcy = trunc(h / 16);
            for (int i = 0; i < 16; i++)
                for (int j = 0; j < 16; j++)
                {
                    int Idx = 16 * i + j;
                    g2.setColor(myPalette256.getColorByIdx(Idx));
                    g2.fillRect(fcx * i, fcy * j, fcx, fcy);
                }

        }
        catch (Exception e)
        {
            e.printStackTrace();
        } 
    }
     //*/        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        Point mouseXY = this.getMousePosition();
        int EWE = getIdxPaletteByXY(mouseXY.x, mouseXY.y);
        afficherMessageFmt("getIdxPaletteByXY(%d, %d) = %d", mouseXY.x, mouseXY.y, EWE);
        if (EWE >= 0) fCurrentIdxCouleur = EWE;
                
    }//GEN-LAST:event_formMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
