// Evaluateur d'expressions: 
// http://www.objecthunter.net/exp4j/
package com.ghtopo.javaghtopo;

import static GHTopoOperationnel.Constantes.*;
import static GHTopoOperationnel.GeneralFunctions.*;
import static GHTopoOperationnel.TCallDialogs.getGHTopoDirectory;
import static UtilsComposants.TOperationsSurComposants.remplirCombosListesSystem;
import GHTopoOperationnel.TConvertisseurCoordonnees;
import GHTopoOperationnel.TSAGeoMag;
import GHTopoOperationnel.TCalculateurDeclimag;
import GHTopoOperationnel.Types.TPoint2Df;
import java.io.File;
import net.objecthunter.exp4j.Expression;
import net.objecthunter.exp4j.ExpressionBuilder;

public class TdlgCalculette extends javax.swing.JDialog 
{
    private int fModalResult = mrNONE;
    private TConvertisseurCoordonnees myConvertisseur;
    private boolean fConvertisseurOK = false;
    private TSAGeoMag myDeclimag;
    private TCalculateurDeclimag myCalculateurDeclimag = null;
    private boolean fDeclimagOK = false;
     
    public int getModalResult()
    {
        return fModalResult;
    }        
    public void initialiserDlg()
    {
        this.setTitle("Calculette - Convertisseur");
        myConvertisseur = new TConvertisseurCoordonnees();
        fConvertisseurOK = myConvertisseur.initialiser();
        myDeclimag = new TSAGeoMag();
        myCalculateurDeclimag = new TCalculateurDeclimag();
        fDeclimagOK = myCalculateurDeclimag.initialiser(getGHTopoDirectory() + File.separator + "IGRF");
        // activer les panneaux Convertisseur et eclinaison
        pnlConversionCoords.setEnabled(fConvertisseurOK);
        pnlDeclinaisonMagnetique.setEnabled(fDeclimagOK);

        try
        {
            // panneau convertisseur de coordonnees
            if (fConvertisseurOK)
            {    
                // remplissage des combos
                remplirCombosListesSystem(cmbSystSrc, myConvertisseur);
                remplirCombosListesSystem(cmbSystTgt, myConvertisseur);
            }
            // panneau déclinaison magnétique
            if (fDeclimagOK)
            {    
                ; // en attente
            }    
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }    
    }    
       
    
    public TdlgCalculette() {
        initComponents();
        pnlConversionCoords.setEnabled(false);
        pnlDeclinaisonMagnetique.setEnabled(false);
        this.setLocationRelativeTo(null); // centrée
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClose = new javax.swing.JButton();
        pnlConversionCoords = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbSystSrc = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cmbSystTgt = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        editXSource = new javax.swing.JFormattedTextField();
        editYSource = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        editXCible = new javax.swing.JFormattedTextField();
        editYCible = new javax.swing.JFormattedTextField();
        pnlEvalExpr = new javax.swing.JPanel();
        btnEval = new javax.swing.JButton();
        editExpression = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pnlDeclinaisonMagnetique = new javax.swing.JPanel();
        btnDeclimagWMM = new javax.swing.JButton();
        editDeclJour = new javax.swing.JTextField();
        editDeclMois = new javax.swing.JTextField();
        editDeclAnnee = new javax.swing.JTextField();
        editdeclinaison = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        btnDeclimagIGRF = new javax.swing.JButton();
        editLongitude = new javax.swing.JTextField();
        editLatitude = new javax.swing.JTextField();
        editAltitude = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnClose.setText("Fermer");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        pnlConversionCoords.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Système source");

        cmbSystSrc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Système cible");

        cmbSystTgt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText(">>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<<");

        jLabel5.setText("Source");

        jLabel3.setText("X =");

        jLabel4.setText("Y =");

        editXSource.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00#######"))));

        editYSource.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00#######"))));

        jLabel6.setText("Cible");

        editXCible.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00#######"))));

        editYCible.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00#######"))));

        javax.swing.GroupLayout pnlConversionCoordsLayout = new javax.swing.GroupLayout(pnlConversionCoords);
        pnlConversionCoords.setLayout(pnlConversionCoordsLayout);
        pnlConversionCoordsLayout.setHorizontalGroup(
            pnlConversionCoordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConversionCoordsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConversionCoordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConversionCoordsLayout.createSequentialGroup()
                        .addGroup(pnlConversionCoordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(pnlConversionCoordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbSystSrc, 0, 461, Short.MAX_VALUE)
                            .addComponent(cmbSystTgt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(208, 208, 208))
                    .addGroup(pnlConversionCoordsLayout.createSequentialGroup()
                        .addGroup(pnlConversionCoordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlConversionCoordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlConversionCoordsLayout.createSequentialGroup()
                                .addGroup(pnlConversionCoordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editYSource, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(editXSource, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlConversionCoordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlConversionCoordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editXCible, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editYCible, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlConversionCoordsLayout.setVerticalGroup(
            pnlConversionCoordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConversionCoordsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlConversionCoordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSystSrc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConversionCoordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbSystTgt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addGroup(pnlConversionCoordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConversionCoordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(editXSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(editXCible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConversionCoordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(editYSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(editYCible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnlEvalExpr.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnEval.setText("Evaluer");
        btnEval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvalActionPerformed(evt);
            }
        });

        editExpression.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editExpressionActionPerformed(evt);
            }
        });

        jLabel7.setText("Expression");

        javax.swing.GroupLayout pnlEvalExprLayout = new javax.swing.GroupLayout(pnlEvalExpr);
        pnlEvalExpr.setLayout(pnlEvalExprLayout);
        pnlEvalExprLayout.setHorizontalGroup(
            pnlEvalExprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEvalExprLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editExpression, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEval, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlEvalExprLayout.setVerticalGroup(
            pnlEvalExprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEvalExprLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEvalExprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEval)
                    .addComponent(editExpression, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pnlDeclinaisonMagnetique.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnDeclimagWMM.setText("Déclinaison WMM");
        btnDeclimagWMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeclimagWMMActionPerformed(evt);
            }
        });

        editDeclJour.setText("01");

        editDeclMois.setText("01");

        editDeclAnnee.setText("2010");

        editdeclinaison.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00#######"))));

        jLabel8.setText("Declinaisons magnetiques (WMM model)");

        btnDeclimagIGRF.setText("Déclinaison (IGRF)");
        btnDeclimagIGRF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeclimagIGRFActionPerformed(evt);
            }
        });

        editLongitude.setText("0.01");

        editLatitude.setText("43.08");

        editAltitude.setText("400");

        javax.swing.GroupLayout pnlDeclinaisonMagnetiqueLayout = new javax.swing.GroupLayout(pnlDeclinaisonMagnetique);
        pnlDeclinaisonMagnetique.setLayout(pnlDeclinaisonMagnetiqueLayout);
        pnlDeclinaisonMagnetiqueLayout.setHorizontalGroup(
            pnlDeclinaisonMagnetiqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeclinaisonMagnetiqueLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlDeclinaisonMagnetiqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDeclinaisonMagnetiqueLayout.createSequentialGroup()
                        .addGroup(pnlDeclinaisonMagnetiqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(pnlDeclinaisonMagnetiqueLayout.createSequentialGroup()
                                .addComponent(editDeclJour, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(editDeclMois, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editDeclAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlDeclinaisonMagnetiqueLayout.createSequentialGroup()
                        .addComponent(editLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editAltitude, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlDeclinaisonMagnetiqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDeclimagIGRF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeclimagWMM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editdeclinaison, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))))
        );
        pnlDeclinaisonMagnetiqueLayout.setVerticalGroup(
            pnlDeclinaisonMagnetiqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeclinaisonMagnetiqueLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDeclinaisonMagnetiqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editDeclJour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editDeclMois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editDeclAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDeclinaisonMagnetiqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeclimagWMM)
                    .addComponent(editdeclinaison, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editAltitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeclimagIGRF)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlEvalExpr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlConversionCoords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlDeclinaisonMagnetique, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlEvalExpr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlConversionCoords, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDeclinaisonMagnetique, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        fModalResult = mrCLOSE;
        //this.setVisible(false);  // ferme le dialogue
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        double qx = ensureConvertStrToNumber(editXSource.getText(), 0.00);
        double qy = ensureConvertStrToNumber(editYSource.getText(), 0.00);
        TPoint2Df p1 = makeTPoint2Df(qx , qy);
        TPoint2Df p2 = myConvertisseur.conversionByIdx(cmbSystSrc.getSelectedIndex(),
                                                       cmbSystTgt.getSelectedIndex(),
                                                       p1.X, p1.Y);
        editXCible.setValue(p2.X);
        editYCible.setValue(p2.Y);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void editExpressionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editExpressionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editExpressionActionPerformed

    private void btnEvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvalActionPerformed
        // TODO add your handling code here:
        ExpressionBuilder fEvaluateurExpr = new ExpressionBuilder(editExpression.getText().trim());
        Expression Expr = fEvaluateurExpr.build();
        Double resultat = new Double(Expr.evaluate());
        editExpression.setText(resultat.toString());
        
    }//GEN-LAST:event_btnEvalActionPerformed

    private void btnDeclimagWMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeclimagWMMActionPerformed
        // TODO add your handling code here:
        double lon  = ensureConvertStrToNumber(editLongitude.getText().trim(),  0.00);
        double lat  = ensureConvertStrToNumber(editLatitude.getText().trim(), 43.00);
        double alt  = ensureConvertStrToNumber(editAltitude.getText().trim(), 0.4);
        int YYYY = strToIntDef(editDeclAnnee.getText().trim(), 2010);
        double decl = myDeclimag.getDeclination(lat, lon, YYYY, alt / 1000);
        editdeclinaison.setText(sprintf("%.8f", decl));
    }//GEN-LAST:event_btnDeclimagWMMActionPerformed

    private void btnDeclimagIGRFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeclimagIGRFActionPerformed
        // TODO add your handling code here: 
        if (fDeclimagOK)
        {
            int JJ   = strToIntDef(editDeclJour.getText().trim(), 1);
            int MM = strToIntDef(editDeclMois.getText().trim(), 1);
            int YYYY = strToIntDef(editDeclAnnee.getText().trim(), 2012);

            double lon  = ensureConvertStrToNumber(editLongitude.getText().trim(),  0.00);
            double lat  = ensureConvertStrToNumber(editLatitude.getText().trim(), 43.00);
            double alt  = ensureConvertStrToNumber(editAltitude.getText().trim(), 0.4);
            double decl = -666.00;
            try
            {
                decl = myCalculateurDeclimag.CalcDeclimag(lon, lat, alt, YYYY, MM, JJ);
                editdeclinaison.setText(sprintf("%.8f", decl));                
            }   
            catch (Exception e)
            {
                e.printStackTrace();
            }
        }    
    }//GEN-LAST:event_btnDeclimagIGRFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TdlgCalculette.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TdlgCalculette.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TdlgCalculette.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TdlgCalculette.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TdlgCalculette().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDeclimagIGRF;
    private javax.swing.JButton btnDeclimagWMM;
    private javax.swing.JButton btnEval;
    private javax.swing.JComboBox cmbSystSrc;
    private javax.swing.JComboBox cmbSystTgt;
    private javax.swing.JTextField editAltitude;
    private javax.swing.JTextField editDeclAnnee;
    private javax.swing.JTextField editDeclJour;
    private javax.swing.JTextField editDeclMois;
    private javax.swing.JTextField editExpression;
    private javax.swing.JTextField editLatitude;
    private javax.swing.JTextField editLongitude;
    private javax.swing.JFormattedTextField editXCible;
    private javax.swing.JFormattedTextField editXSource;
    private javax.swing.JFormattedTextField editYCible;
    private javax.swing.JFormattedTextField editYSource;
    private javax.swing.JFormattedTextField editdeclinaison;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel pnlConversionCoords;
    private javax.swing.JPanel pnlDeclinaisonMagnetique;
    private javax.swing.JPanel pnlEvalExpr;
    // End of variables declaration//GEN-END:variables
}
