package com.ghtopo.javaghtopo;
import GHTopoOperationnel.Types.TViseeEnAntenne;
import GHTopoOperationnel.TToporobotStructure;
import java.util.ResourceBundle;
import javax.swing.table.DefaultTableModel;


public class TCadreViseeAntenne extends javax.swing.JPanel 
{
    private ResourceBundle fMyResourceBundle = null;
    private TToporobotStructure myFDocuTopo;
    private String getResourceByKey(String k)
    {
        return fMyResourceBundle.getString(k);
    }        
   
    public void initialiserCadreViseesAntennes(TToporobotStructure dt)
    {
        this.myFDocuTopo = dt;
        listerLesViseesAntennes();
    }
    private void listerLesViseesAntennes()
    {
        int nb = this.myFDocuTopo.getNbViseesAntenne();
        if (nb > 0)
        {   
            ((DefaultTableModel) grdViseesAntennes.getModel()).setRowCount(nb);
            for (int i = 0; i < nb; i++)
            {
                TViseeEnAntenne myVisee = this.myFDocuTopo.getViseeEnAntenne(i);
                grdViseesAntennes.setValueAt(myVisee.SerieDepart, i, 0);
                grdViseesAntennes.setValueAt(myVisee.PtDepart, i, 1);
                grdViseesAntennes.setValueAt(myVisee.IDTerrainStation, i, 2);
                grdViseesAntennes.setValueAt(myVisee.Reseau, i, 3);
                grdViseesAntennes.setValueAt(myVisee.Secteur, i, 4);
                grdViseesAntennes.setValueAt(myVisee.Code, i, 5);
                grdViseesAntennes.setValueAt(myVisee.Expe, i, 6);
                grdViseesAntennes.setValueAt(myVisee.Longueur, i, 7);
                grdViseesAntennes.setValueAt(myVisee.Azimut, i, 8);
                grdViseesAntennes.setValueAt(myVisee.Pente, i, 9);
                grdViseesAntennes.setValueAt(myVisee.Commentaires, i, 10);
            }
        }    
    }   
    //--------------------------------------------------------------------------
    // constructeur
    public TCadreViseeAntenne() {
        this.fMyResourceBundle = java.util.ResourceBundle.getBundle("com/ghtopo/javaghtopo/Bundle");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        grdViseesAntennes = new javax.swing.JTable();

        grdViseesAntennes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serie", "Station", "IDTerrain", "Reseau", "Secteur", "Code", "Expé", "Longueur", "Azimut", "Pente", "Commentaires"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(grdViseesAntennes);
        if (grdViseesAntennes.getColumnModel().getColumnCount() > 0) {
            grdViseesAntennes.getColumnModel().getColumn(0).setPreferredWidth(60);
            grdViseesAntennes.getColumnModel().getColumn(1).setPreferredWidth(60);
            grdViseesAntennes.getColumnModel().getColumn(3).setPreferredWidth(60);
            grdViseesAntennes.getColumnModel().getColumn(5).setPreferredWidth(60);
            grdViseesAntennes.getColumnModel().getColumn(6).setPreferredWidth(60);
            grdViseesAntennes.getColumnModel().getColumn(7).setPreferredWidth(100);
            grdViseesAntennes.getColumnModel().getColumn(8).setPreferredWidth(80);
            grdViseesAntennes.getColumnModel().getColumn(9).setPreferredWidth(80);
            grdViseesAntennes.getColumnModel().getColumn(10).setPreferredWidth(300);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable grdViseesAntennes;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
