/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.ghtopo.javaghtopo;
import static GHTopoOperationnel.GeneralFunctions.*;
import static GHTopoOperationnel.TCallDialogs.*;

import GHTopoOperationnel.Types.TSecteur;
import java.awt.Color;
import java.util.ResourceBundle;

/**
 *
 * @author jean-pierre.cassou
 */
public class TCadreSecteur extends javax.swing.JPanel {
    private ResourceBundle fMyResourceBundle = null;
    private String getResourceByKey(String k)
    {
        return fMyResourceBundle.getString(k);
    }        
   
    public void initialiserCadreSecteur (TSecteur sc)
    {
        editIdxSecteur.setText(intToStr(sc.IdxSecteur));
        editNomSecteur.setText(sc.NomSecteur);
        Color c = new Color(sc.CouleurSecteurR, sc.CouleurSecteurG, sc.CouleurSecteurB);
        btnColorSecteur.setOpaque(true);
        btnColorSecteur.setBackground(c);
        btnColorSecteur.setText(sprintf("%02X%02X%02X", sc.CouleurSecteurR, sc.CouleurSecteurG, sc.CouleurSecteurB));
        
    }  
    public TSecteur getSecteurFromForm()
    {
        TSecteur result = new TSecteur();
        result.IdxSecteur = strToIntDef(editIdxSecteur.getText().trim(), 0);
        result.NomSecteur = editNomSecteur.getText().trim();
        Color c = btnColorSecteur.getBackground();
        result.CouleurSecteurR = c.getRed();
        result.CouleurSecteurG = c.getGreen();
        result.CouleurSecteurB = c.getBlue();
        return result;
    } 
       
    public TCadreSecteur() {
        this.fMyResourceBundle = java.util.ResourceBundle.getBundle("com/ghtopo/javaghtopo/Bundle");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        editIdxSecteur = new javax.swing.JTextField();
        editNomSecteur = new javax.swing.JTextField();
        btnColorSecteur = new javax.swing.JButton();

        jLabel1.setText("Numero");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        editNomSecteur.setNextFocusableComponent(editIdxSecteur);

        btnColorSecteur.setBackground(new java.awt.Color(255, 51, 51));
        btnColorSecteur.setForeground(new java.awt.Color(255, 102, 102));
        btnColorSecteur.setText("toto");
        btnColorSecteur.setAutoscrolls(true);
        btnColorSecteur.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnColorSecteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorSecteurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editNomSecteur)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnColorSecteur, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 209, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(editIdxSecteur, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editIdxSecteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(btnColorSecteur, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editNomSecteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnColorSecteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorSecteurActionPerformed
        // TODO add your handling code here:
        Color c = btnColorSecteur.getBackground();
        afficherMessage(c.toString());
        c = ChooseColor(this.btnColorSecteur, "Couleur de secteur", c);
        //afficherMessage(c.toString());
        btnColorSecteur.setBackground(c);
        btnColorSecteur.setText(sprintf("%X", c.getRGB()));
    }//GEN-LAST:event_btnColorSecteurActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColorSecteur;
    private javax.swing.JTextField editIdxSecteur;
    private javax.swing.JTextField editNomSecteur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
