/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.ghtopo.javaghtopo;
import static GHTopoOperationnel.Constantes.*;
import static GHTopoOperationnel.GeneralFunctions.*;
import GHTopoOperationnel.TCallDialogs;
import GHTopoOperationnel.TTableDesEntites;


/**
 *
 * @author jean-pierre.cassou
 */
public class TdlgVue2D extends javax.swing.JDialog {
    private TTableDesEntites myTableEntites;
    private int fModalResult = mrNONE;
    public int getModalResult()
    {
        return fModalResult;
    }       
    private void setMenusElementsDrawn(long ElementsDraw)
    {
        mnuDoEntrances.setSelected(IsInSet(edENTRANCES, ElementsDraw));
        mnuDoPolygonale.setSelected(IsInSet(edPolygonals, ElementsDraw));
        mnuDoSilhouettes.setSelected(IsInSet(edFillGalerie, ElementsDraw));
        mnuDoCrossSections.setSelected(IsInSet(edCrossSections, ElementsDraw));
        mnuDoStations.setSelected(IsInSet(edStations, ElementsDraw));
        mnuDoIDStations.setSelected(IsInSet(edIDStations, ElementsDraw));
        mnuDoAltitudes.setSelected(IsInSet(edAltitudes, ElementsDraw));
        mnuDoCotation.setSelected(IsInSet(edCotes, ElementsDraw));
        //mnuDo.setSelected(IsInSet(ed, ElementsDraw));        
    }        
    public void initialiserLaVue2D(TTableDesEntites t)
    {
        myTableEntites = t;
        tVue2D1.initialiseVue2D(myTableEntites, lbCoordSouris, lbInfosStation);
        editFiltres.setText("");
        setMenusElementsDrawn(tVue2D1.getElementsDrawn());
    }        
     
    public TdlgVue2D() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    private void SelectDeselectFlagsVue2D(int Flag, boolean b)
    {
        long EWE = tVue2D1.getElementsDrawn();
        EWE = setOnOffFlagInSet(Flag, EWE, b);
        tVue2D1.setElementsDrawn(EWE);
    }   
    private void BasculerFlagVue2D(int Flag)
    {
        long EWE = tVue2D1.getElementsDrawn();
        EWE = basculerOnOffFlagInSet(Flag, EWE);
        tVue2D1.setElementsDrawn(EWE);
    }        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        popupMenuVue2D = new javax.swing.JPopupMenu();
        mnuDoEntrances = new javax.swing.JCheckBoxMenuItem();
        mnuDoPolygonale = new javax.swing.JCheckBoxMenuItem();
        mnuDoSilhouettes = new javax.swing.JCheckBoxMenuItem();
        mnuDoCrossSections = new javax.swing.JCheckBoxMenuItem();
        mnuDoStations = new javax.swing.JCheckBoxMenuItem();
        mnuDoIDStations = new javax.swing.JCheckBoxMenuItem();
        mnuDoCotation = new javax.swing.JCheckBoxMenuItem();
        mnuDoAltitudes = new javax.swing.JCheckBoxMenuItem();
        mnuDoJonctionsOnly = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuRadioDessinByDEPTH = new javax.swing.JRadioButtonMenuItem();
        mnuRadioDessinByRESEAU = new javax.swing.JRadioButtonMenuItem();
        mnuRadioDessinBySECTEURS = new javax.swing.JRadioButtonMenuItem();
        mnuRadioDessinBySEANCES = new javax.swing.JRadioButtonMenuItem();
        grpBtnModesRepresentation = new javax.swing.ButtonGroup();
        tVue2D1 = new com.ghtopo.javaghtopo.TVue2D();
        btnClose = new javax.swing.JButton();
        lbCoordSouris = new javax.swing.JLabel();
        lbInfosStation = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnApplyMetaFiltre = new javax.swing.JButton();
        editFiltres = new javax.swing.JTextField();
        btnResetVue = new javax.swing.JButton();

        mnuDoEntrances.setSelected(true);
        mnuDoEntrances.setText("Entrées");
        mnuDoEntrances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDoEntrancesActionPerformed(evt);
            }
        });
        popupMenuVue2D.add(mnuDoEntrances);

        mnuDoPolygonale.setSelected(true);
        mnuDoPolygonale.setText("Polygonales");
        mnuDoPolygonale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDoPolygonaleActionPerformed(evt);
            }
        });
        popupMenuVue2D.add(mnuDoPolygonale);

        mnuDoSilhouettes.setSelected(true);
        mnuDoSilhouettes.setText("Silhouettes");
        mnuDoSilhouettes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDoSilhouettesActionPerformed(evt);
            }
        });
        popupMenuVue2D.add(mnuDoSilhouettes);

        mnuDoCrossSections.setSelected(true);
        mnuDoCrossSections.setText("Sections");
        mnuDoCrossSections.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDoCrossSectionsActionPerformed(evt);
            }
        });
        popupMenuVue2D.add(mnuDoCrossSections);

        mnuDoStations.setSelected(true);
        mnuDoStations.setText("Stations");
        mnuDoStations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDoStationsActionPerformed(evt);
            }
        });
        popupMenuVue2D.add(mnuDoStations);

        mnuDoIDStations.setSelected(true);
        mnuDoIDStations.setText("ID stations");
        popupMenuVue2D.add(mnuDoIDStations);

        mnuDoCotation.setSelected(true);
        mnuDoCotation.setText("Cotation");
        popupMenuVue2D.add(mnuDoCotation);

        mnuDoAltitudes.setSelected(true);
        mnuDoAltitudes.setText("Altitudes");
        popupMenuVue2D.add(mnuDoAltitudes);

        mnuDoJonctionsOnly.setSelected(true);
        mnuDoJonctionsOnly.setText("Jonctions");
        mnuDoJonctionsOnly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDoJonctionsOnlyActionPerformed(evt);
            }
        });
        popupMenuVue2D.add(mnuDoJonctionsOnly);

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");
        popupMenuVue2D.add(jCheckBoxMenuItem2);
        popupMenuVue2D.add(jSeparator1);

        grpBtnModesRepresentation.add(mnuRadioDessinByDEPTH);
        mnuRadioDessinByDEPTH.setSelected(true);
        mnuRadioDessinByDEPTH.setText("Profondeurs");
        mnuRadioDessinByDEPTH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRadioDessinByDEPTHActionPerformed(evt);
            }
        });
        popupMenuVue2D.add(mnuRadioDessinByDEPTH);

        grpBtnModesRepresentation.add(mnuRadioDessinByRESEAU);
        mnuRadioDessinByRESEAU.setText("Par réseaux");
        mnuRadioDessinByRESEAU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRadioDessinByRESEAUActionPerformed(evt);
            }
        });
        popupMenuVue2D.add(mnuRadioDessinByRESEAU);

        grpBtnModesRepresentation.add(mnuRadioDessinBySECTEURS);
        mnuRadioDessinBySECTEURS.setText("Par secteurs");
        mnuRadioDessinBySECTEURS.setToolTipText("");
        mnuRadioDessinBySECTEURS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRadioDessinBySECTEURSActionPerformed(evt);
            }
        });
        popupMenuVue2D.add(mnuRadioDessinBySECTEURS);

        grpBtnModesRepresentation.add(mnuRadioDessinBySEANCES);
        mnuRadioDessinBySEANCES.setText("Par séances");
        mnuRadioDessinBySEANCES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRadioDessinBySEANCESActionPerformed(evt);
            }
        });
        popupMenuVue2D.add(mnuRadioDessinBySEANCES);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, popupMenuVue2D, org.jdesktop.beansbinding.ObjectProperty.create(), tVue2D1, org.jdesktop.beansbinding.BeanProperty.create("componentPopupMenu"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout tVue2D1Layout = new javax.swing.GroupLayout(tVue2D1);
        tVue2D1.setLayout(tVue2D1Layout);
        tVue2D1Layout.setHorizontalGroup(
            tVue2D1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        tVue2D1Layout.setVerticalGroup(
            tVue2D1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );

        btnClose.setText("Fermer");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        lbCoordSouris.setText("jLabel1");
        lbCoordSouris.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbCoordSouris.setMaximumSize(new java.awt.Dimension(0, 23));
        lbCoordSouris.setMinimumSize(new java.awt.Dimension(100, 23));

        lbInfosStation.setText("jLabel2");
        lbInfosStation.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbInfosStation.setMaximumSize(new java.awt.Dimension(38, 23));
        lbInfosStation.setMinimumSize(new java.awt.Dimension(38, 23));

        jLabel1.setText("Filtres");

        btnApplyMetaFiltre.setText("Filtrer");
        btnApplyMetaFiltre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyMetaFiltreActionPerformed(evt);
            }
        });

        btnResetVue.setText("Reset");
        btnResetVue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetVueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tVue2D1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editFiltres, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnApplyMetaFiltre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnResetVue)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbCoordSouris, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbInfosStation, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editFiltres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApplyMetaFiltre)
                    .addComponent(jLabel1)
                    .addComponent(btnResetVue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tVue2D1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCoordSouris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbInfosStation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose)))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        fModalResult = mrCLOSE;
        //this.setVisible(false);  // ferme le dialogue
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnApplyMetaFiltreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyMetaFiltreActionPerformed
        // TODO add your handling code here:
        String s = editFiltres.getText();
        tVue2D1.appliquerMetaFiltre(s);
    }//GEN-LAST:event_btnApplyMetaFiltreActionPerformed

    private void btnResetVueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetVueActionPerformed
        // TODO add your handling code here:
        tVue2D1.resetVue();
    }//GEN-LAST:event_btnResetVueActionPerformed

    private void mnuDoCrossSectionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDoCrossSectionsActionPerformed
        // TODO add your handling code here:
        BasculerFlagVue2D(edCrossSections);
    }//GEN-LAST:event_mnuDoCrossSectionsActionPerformed

    private void mnuDoPolygonaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDoPolygonaleActionPerformed
        // TODO add your handling code here:
        BasculerFlagVue2D(edPolygonals);           
    }//GEN-LAST:event_mnuDoPolygonaleActionPerformed

    private void mnuDoSilhouettesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDoSilhouettesActionPerformed
        // TODO add your handling code here:
        BasculerFlagVue2D(edFillGalerie);
    }//GEN-LAST:event_mnuDoSilhouettesActionPerformed

    private void mnuDoEntrancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDoEntrancesActionPerformed
        // TODO add your handling code here:
        BasculerFlagVue2D(edENTRANCES);
    }//GEN-LAST:event_mnuDoEntrancesActionPerformed

    private void mnuDoStationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDoStationsActionPerformed
        // TODO add your handling code here:
        BasculerFlagVue2D(edStations);        
    }//GEN-LAST:event_mnuDoStationsActionPerformed

    private void mnuRadioDessinByDEPTHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRadioDessinByDEPTHActionPerformed
        // TODO add your handling code here:
        tVue2D1.setModeRepresentationReseau(rgDEPTH);
    }//GEN-LAST:event_mnuRadioDessinByDEPTHActionPerformed

    private void mnuRadioDessinByRESEAUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRadioDessinByRESEAUActionPerformed
        // TODO add your handling code here:
        tVue2D1.setModeRepresentationReseau(rgRESEAUX);
    }//GEN-LAST:event_mnuRadioDessinByRESEAUActionPerformed

    private void mnuRadioDessinBySECTEURSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRadioDessinBySECTEURSActionPerformed
        // TODO add your handling code here:
        tVue2D1.setModeRepresentationReseau(rgSECTEURS);
    }//GEN-LAST:event_mnuRadioDessinBySECTEURSActionPerformed

    private void mnuRadioDessinBySEANCESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRadioDessinBySEANCESActionPerformed
        // TODO add your handling code here:
        tVue2D1.setModeRepresentationReseau(rgSEANCES);
    }//GEN-LAST:event_mnuRadioDessinBySEANCESActionPerformed

    private void mnuDoJonctionsOnlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDoJonctionsOnlyActionPerformed
        // TODO add your handling code here:
        SelectDeselectFlagsVue2D(edJonctions, mnuDoCrossSections.isSelected());
    }//GEN-LAST:event_mnuDoJonctionsOnlyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TdlgVue2D.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TdlgVue2D.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TdlgVue2D.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TdlgVue2D.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TdlgVue2D().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApplyMetaFiltre;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnResetVue;
    private javax.swing.JTextField editFiltres;
    private javax.swing.ButtonGroup grpBtnModesRepresentation;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lbCoordSouris;
    private javax.swing.JLabel lbInfosStation;
    private javax.swing.JCheckBoxMenuItem mnuDoAltitudes;
    private javax.swing.JCheckBoxMenuItem mnuDoCotation;
    private javax.swing.JCheckBoxMenuItem mnuDoCrossSections;
    private javax.swing.JCheckBoxMenuItem mnuDoEntrances;
    private javax.swing.JCheckBoxMenuItem mnuDoIDStations;
    private javax.swing.JCheckBoxMenuItem mnuDoJonctionsOnly;
    private javax.swing.JCheckBoxMenuItem mnuDoPolygonale;
    private javax.swing.JCheckBoxMenuItem mnuDoSilhouettes;
    private javax.swing.JCheckBoxMenuItem mnuDoStations;
    private javax.swing.JRadioButtonMenuItem mnuRadioDessinByDEPTH;
    private javax.swing.JRadioButtonMenuItem mnuRadioDessinByRESEAU;
    private javax.swing.JRadioButtonMenuItem mnuRadioDessinBySEANCES;
    private javax.swing.JRadioButtonMenuItem mnuRadioDessinBySECTEURS;
    private javax.swing.JPopupMenu popupMenuVue2D;
    private com.ghtopo.javaghtopo.TVue2D tVue2D1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
